In [112]:
# thêm thư viện
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import ipywidgets as widgets
from IPython.display import display, clear_output
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import warnings
# Bỏ qua tất cả các cảnh báo
warnings.filterwarnings("ignore")

In [113]:
import os

new_dir = r"D:\University\UDPTDLTM_final_project"

os.chdir(new_dir)

print(os.getcwd())

D:\University\UDPTDLTM_final_project

In [114]:
data = pd.read_csv('./Data/DVN_2024-09-28.csv')

In [115]:
data

,Ngày,KLNY,KLCPĐLH,Tham chiếu,Trần,Sàn,Tổng KLGD,Tổng GTGD,Vốn hóa TT,Mở cửa,...,Khớp lệnh,Khớp lệnh.1,Tổng lệnh đặt,Tổng lệnh đặt.1,Tổng lệnh đặt.2,Tổng KL đặt,Tổng KL đặt.1,Tổng KL đặt.2,Thỏa thuận,Thỏa thuận.1
0,Ngày,KLNY,KLCPĐLH,Tham chiếu,Trần,Sàn,Tổng KLGD,Tổng GTGD,Vốn hóa TT,Mở cửa,...,KL,GT,Mua,Bán,Mua - Bán,Mua,Bán,Mua - Bán,KL,GT
1,27/09/2024,237000000,237000000,24000,27600,20400,111472,2664,5641,24300,...,111472,2664,225,139,86,530800,240100,290700,-,NaN
2,26/09/2024,237000000,237000000,24300,27900,20700,143969,3455,5688,24300,...,143969,3455,240,160,80,498800,321400,177400,-,NaN
3,25/09/2024,237000000,237000000,24900,28600,21200,272332,6622,5735,25300,...,272332,6622,423,181,242,312500,508700,-196200,-,NaN
4,24/09/2024,237000000,237000000,25300,29000,21600,404105,10328,5901,25600,...,168105,4192,284,149,135,214600,258000,-43400,236000,6136.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,09/10/2023,237000000,237000000,18600,21300,15900,56149,1049,4432,18500,...,56149,1049,79,87,-8,75538,111928,-36390,-,NaN
244,06/10/2023,237000000,237000000,18500,21200,15800,20817,386,4408,18400,...,20817,386,58,70,-12,48027,65474,-17447,-,NaN
245,05/10/2023,237000000,237000000,18500,21200,15800,5000,93,4432,18700,...,5000,93,43,55,-12,48757,56764,-8007,-,NaN
246,04/10/2023,237000000,237000000,18700,21500,15900,14300,264,4408,18300,...,14300,264,54,54,-,46982,91553,-44571,-,NaN
247,03/10/2023,237000000,237000000,18900,21700,16100,21101,394,4408,19000,...,21101,394,51,73,-22,38411,101343,-62932,-,NaN

In [116]:
# xóa dòng đầu vì dư
data = data.drop(0)
data

,Ngày,KLNY,KLCPĐLH,Tham chiếu,Trần,Sàn,Tổng KLGD,Tổng GTGD,Vốn hóa TT,Mở cửa,...,Khớp lệnh,Khớp lệnh.1,Tổng lệnh đặt,Tổng lệnh đặt.1,Tổng lệnh đặt.2,Tổng KL đặt,Tổng KL đặt.1,Tổng KL đặt.2,Thỏa thuận,Thỏa thuận.1
1,27/09/2024,237000000,237000000,24000,27600,20400,111472,2664,5641,24300,...,111472,2664,225,139,86,530800,240100,290700,-,NaN
2,26/09/2024,237000000,237000000,24300,27900,20700,143969,3455,5688,24300,...,143969,3455,240,160,80,498800,321400,177400,-,NaN
3,25/09/2024,237000000,237000000,24900,28600,21200,272332,6622,5735,25300,...,272332,6622,423,181,242,312500,508700,-196200,-,NaN
4,24/09/2024,237000000,237000000,25300,29000,21600,404105,10328,5901,25600,...,168105,4192,284,149,135,214600,258000,-43400,236000,6136.0
5,23/09/2024,237000000,237000000,25600,29400,21800,55488,1406,5972,25900,...,55488,1406,139,129,10,88000,172900,-84900,-,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,09/10/2023,237000000,237000000,18600,21300,15900,56149,1049,4432,18500,...,56149,1049,79,87,-8,75538,111928,-36390,-,NaN
244,06/10/2023,237000000,237000000,18500,21200,15800,20817,386,4408,18400,...,20817,386,58,70,-12,48027,65474,-17447,-,NaN
245,05/10/2023,237000000,237000000,18500,21200,15800,5000,93,4432,18700,...,5000,93,43,55,-12,48757,56764,-8007,-,NaN
246,04/10/2023,237000000,237000000,18700,21500,15900,14300,264,4408,18300,...,14300,264,54,54,-,46982,91553,-44571,-,NaN
247,03/10/2023,237000000,237000000,18900,21700,16100,21101,394,4408,19000,...,21101,394,51,73,-22,38411,101343,-62932,-,NaN

In [117]:
# đổi format ngày rồi sắp xếp lại thứ tự từ ngày cũ nhất đến ngày mới nhất (biết format hiện tại đang là ngày/tháng/năm, cần đổi sang format chuẩn để sort)
# cột tên là Ngày
data['Ngày'] = pd.to_datetime(data['Ngày'], format='%d/%m/%Y')
data = data.sort_values(by='Ngày', ascending=True).reset_index(drop=True)
data

,Ngày,KLNY,KLCPĐLH,Tham chiếu,Trần,Sàn,Tổng KLGD,Tổng GTGD,Vốn hóa TT,Mở cửa,...,Khớp lệnh,Khớp lệnh.1,Tổng lệnh đặt,Tổng lệnh đặt.1,Tổng lệnh đặt.2,Tổng KL đặt,Tổng KL đặt.1,Tổng KL đặt.2,Thỏa thuận,Thỏa thuận.1
0,2023-10-03,237000000,237000000,18900,21700,16100,21101,394,4408,19000,...,21101,394,51,73,-22,38411,101343,-62932,-,NaN
1,2023-10-04,237000000,237000000,18700,21500,15900,14300,264,4408,18300,...,14300,264,54,54,-,46982,91553,-44571,-,NaN
2,2023-10-05,237000000,237000000,18500,21200,15800,5000,93,4432,18700,...,5000,93,43,55,-12,48757,56764,-8007,-,NaN
3,2023-10-06,237000000,237000000,18500,21200,15800,20817,386,4408,18400,...,20817,386,58,70,-12,48027,65474,-17447,-,NaN
4,2023-10-09,237000000,237000000,18600,21300,15900,56149,1049,4432,18500,...,56149,1049,79,87,-8,75538,111928,-36390,-,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,2024-09-23,237000000,237000000,25600,29400,21800,55488,1406,5972,25900,...,55488,1406,139,129,10,88000,172900,-84900,-,NaN
243,2024-09-24,237000000,237000000,25300,29000,21600,404105,10328,5901,25600,...,168105,4192,284,149,135,214600,258000,-43400,236000,6136.0
244,2024-09-25,237000000,237000000,24900,28600,21200,272332,6622,5735,25300,...,272332,6622,423,181,242,312500,508700,-196200,-,NaN
245,2024-09-26,237000000,237000000,24300,27900,20700,143969,3455,5688,24300,...,143969,3455,240,160,80,498800,321400,177400,-,NaN
246,2024-09-27,237000000,237000000,24000,27600,20400,111472,2664,5641,24300,...,111472,2664,225,139,86,530800,240100,290700,-,NaN

#### **1. Lý thuyết về Moving Average**
##### **1.1. Định nghĩa:** 
Moving Average (MA) hay còn gọi là Trung bình trượt là một kỹ thuật được sử dụng để làm mượt các biến động của một dữ liệu chuỗi thời gian nhằm xác định xu hướng chính trong một khoảng thời gian nhất định. 

##### **1.2. Ứng dụng của MA**

   **Data thường được sử dụng**
   - **Giá chứng khoán**: MA thường được sử dụng để phân tích giá cổ phiếu, quỹ ETF, và các tài sản tài chính khác.
   - **Chỉ số kinh tế**: MA cũng được sử dụng để phân tích các chỉ số kinh tế như GDP, lạm phát, và tỷ lệ thất nghiệp.
   - **Giá hàng hóa**: MA được áp dụng để phân tích giá các hàng hóa như vàng, dầu, và các nguyên liệu thô khác.
   - **Dữ liệu thời gian khác**: MA có thể được sử dụng trong nhiều loại dữ liệu thời gian khác như dữ liệu nhiệt độ, lưu lượng truy cập trang web, và số liệu thống kê khác.

   **Mục đích sử dụng**

   1. **Xác định xu hướng**: MA giúp xác định xu hướng dài hạn của giá tài sản bằng cách làm mượt các biến động ngắn hạn.
   2. **Tín hiệu giao dịch**: MA được sử dụng để tạo ra các tín hiệu mua và bán (trong chứng khoán).
   3. **Hỗ trợ và kháng cự**: MA có thể hoạt động như các mức hỗ trợ và kháng cự. Giá thường có xu hướng bật lại từ đường MA trong một xu hướng mạnh.
   4. **Đánh giá độ mạnh của xu hướng**: Khoảng cách giữa giá và đường MA có thể cho biết độ mạnh của xu hướng. Khoảng cách lớn cho thấy xu hướng mạnh, trong khi khoảng cách nhỏ cho thấy xu hướng yếu.

##### **1.3. Các bước thực hiện MA**
1. **Thu thập dữ liệu**: Lấy dữ liệu trong một khoảng thời gian nhất định.
2. **Xác định khoảng thời gian MA**: Chọn khoảng thời gian (n ngày) để tính toán MA.
3. **Tính toán MA**: Tính trung bình cho khoảng thời gian đã chọn (theo SMA, EMA, WMA, VWMA,...)
4. **Vẽ MA lên biểu đồ**: Đặt đường MA lên biểu đồ để dễ dàng quan sát xu hướng.

##### **1.4. Các loại MA phổ biến** 
(Tham khảo: [Investopedia](https://www.investopedia.com/terms/m/movingaverage.asp))

&nbsp; &nbsp; **a. Simple Moving Average (SMA)**:
Là trung bình cộng của các giá trị trong một khoảng thời gian nhất định. Mỗi giá trị trong khoảng thời gian này đều có trọng số như nhau.

&nbsp; &nbsp; Công thức tính:
   $$
   \text{SMA} = \frac{\sum_{i=1}^{n} P_i}{n}
   $$
&nbsp; &nbsp; Trong đó $ P_i $ là giá trị tại ngày thứ $ i $, và $ n $ là số ngày.
- **Ưu điểm**:
   - Dễ tính toán và hiểu.
   - Thích hợp cho phân tích dài hạn.
- **Nhược điểm**:
   - Có độ trễ lớn, không nhạy cảm với các thay đổi gần đây trong dữ liệu.
   - Gán trọng số như nhau cho tất cả các giá trị, không phản ánh được tầm quan trọng của các giá trị gần hiện tại.
- **Ứng dụng**:
   - Thường được sử dụng để xác định các xu hướng dài hạn và làm mượt dữ liệu giá.
   - Hiệu quả trong các thị trường ít biến động.
- **Cài đặt SMA**:
   - `rolling(window=period)`: tạo một "cửa sổ trượt" với độ dài period.
   - Dùng hàm `mean()` để tính trung bình cho mỗi cửa sổ trượt.

In [118]:
def SMA(df, period, column):
    return df[column].rolling(window=period).mean()

&nbsp; &nbsp; **b. Exponential Moving Average (EMA)**: 
Là trung bình trượt có trọng số mà các giá trị gần hiện tại được gán trọng số lớn hơn, giảm dần theo hàm mũ.  
&nbsp; &nbsp; Công thức tính:
   $$
   \text{EMA}_t = P_t \times \frac{2}{n+1} + \text{EMA}_{t-1} \times \left(1 - \frac{2}{n+1}\right)
   $$
&nbsp; &nbsp; Trong đó $ P_t $ là giá tại ngày hiện tại, $ \text{EMA}_{t-1} $ là EMA của ngày trước đó, và $ n $ là số ngày.

   - **Ưu điểm**:
      - Nhạy cảm hơn với các thay đổi gần đây trong dữ liệu, giúp phát hiện xu hướng mới sớm hơn.
      - Ít bị trễ hơn so với SMA.
   - **Nhược điểm**:
      - Có thể gây ra nhiều tín hiệu sai trong thị trường biến động mạnh.
      - Phức tạp hơn trong việc tính toán so với SMA và WMA.
   - **Ứng dụng**
      - Thường được sử dụng trong phân tích kỹ thuật để xác định các điểm mua và bán tiềm năng dựa trên sự thay đổi xu hướng.
      - Hiệu quả trong các thị trường biến động nhanh, nơi việc phát hiện các xu hướng mới sớm là quan trọng.
   - **Cài đặt EMA**: Dùng hàm `ewm()` để tính trung bình trượt theo hàm mũ.
      - `ewm(span=period, adjust=False)`: Tạo một cửa sổ trượt hàm mũ với độ dài span là period. adjust=False để trọng số không bị điều chỉnh lại.

In [119]:
def EMA(df, period, column):
    return df[column].ewm(span=period, adjust=False).mean()

&nbsp; &nbsp; **c. Weighted Moving Average (WMA)**: 
Là trung bình trượt có trọng số mà các giá trị được gán trọng số giảm dần theo thời gian, với trọng số lớn nhất dành cho giá trị gần hiện tại, giảm theo tuyến tính.   
&nbsp; &nbsp; Công thức tính:
   $$
   \text{WMA} = \frac{\sum_{i=1}^{n} w_i P_i}{\sum_{i=1}^{n} w_i}
   $$
&nbsp; &nbsp; Trong đó $ w_i $ là trọng số và $ P_i $ là giá tại ngày thứ $ i $.
- **Ưu điểm**:
   - Đơn giản hơn EMA trong việc tính toán.
   - Gán trọng số lớn hơn cho các giá trị gần hiện tại, nhưng không giảm theo hàm mũ, nên ít nhạy cảm hơn EMA nhưng vẫn nhạy hơn SMA.
- **Nhược điểm**:
   - Không phản ánh mạnh mẽ như EMA đối với các thay đổi gần đây.
   - Vẫn có độ trễ nhưng ít hơn SMA.
- **Ứng dụng**:
   - Thường được sử dụng trong phân tích kỹ thuật, nhưng thích hợp hơn cho các thị trường ít biến động hơn.
   -  Có thể được sử dụng để xác định các xu hướng dài hạn hơn so với EMA.
- **Cài đặt WMA**: 
   - `weights = list(range(1, period + 1))`: Tạo một mảng trọng số tuyến tính từ 1 đến period.
   - `apply(lambda prices: np.dot(prices, weights) / sum(weights), raw=True)`: Áp dụng hàm tính WMA cho mỗi cửa sổ trượt.
      -  np.dot(prices, weights): Tính tích vô hướng của giá và trọng số.
      - / weights.sum(): Chia cho tổng trọng số để chuẩn hóa giá trị.

In [120]:
def WMA(df, period, column):
    weights = list(range(1, period + 1))
    return df[column].rolling(period).apply(lambda prices: np.dot(prices, weights) / sum(weights), raw=True)

&nbsp; &nbsp; **d. Volume-Weighted Moving Average (VWMA)**: 
Là trung bình trượt mà các giá trị giá được gán trọng số dựa trên khối lượng giao dịch. Điều này giúp phản ánh sức mạnh của các mức giá.  
   $$
   \text{VWMA} = \frac{\sum_{i=1}^{n} (P_i \times V_i)}{\sum_{i=1}^{n} V_i}
   $$
&nbsp; &nbsp; Trong đó $ P_i $ là giá tại ngày thứ $ i $, $ V_i $ là khối lượng giao dịch tại ngày thứ $ i $.
- **Ưu điểm**:
   - Phản ánh chính xác hơn giá trị thực tế của giá bằng cách tính đến khối lượng giao dịch.
   - Hiệu quả trong các thị trường có khối lượng giao dịch lớn và biến động mạnh.
- **Nhược điểm**:
   - Phức tạp hơn trong việc tính toán.
   - Có thể ít hiệu quả trong các thị trường có khối lượng giao dịch thấp hoặc không đồng đều.
- **Ứng dụng**:
   - Thường được sử dụng trong phân tích kỹ thuật để xác định các xu hướng dựa trên khối lượng giao dịch.
   - Hiệu quả trong các thị trường có khối lượng giao dịch lớn, nơi mà khối lượng giao dịch là một yếu tố quan trọng trong việc xác định xu hướng giá.
- **Cài đặt VWMA**:
   - Kiểm tra xem có cột khối lượng (Volume) không. Nếu không có, thì tạo một cột khối lượng với giá trị 1.
   - `weights = np.arange(1, period + 1)`: Tạo một mảng trọng số từ 1 đến `period` để áp dụng trong phép tính VWMA.
   - `df[column].rolling(window=period).apply(lambda prices: np.dot(prices, weights) / weights.sum(), raw=True)`: 
     - Tính tổng tích của giá và trọng số trong mỗi cửa sổ trượt bằng cách sử dụng phép nhân điểm (`np.dot`) giữa giá và trọng số, sau đó chia cho tổng trọng số để chuẩn hóa giá trị.

In [121]:
def VWMA(df, period, column, volume_column='Tổng KLGD'):
    weights = np.arange(1, period + 1)
    return df[column].rolling(window=period).apply(lambda prices: np.dot(prices, weights) / weights.sum(), raw=True)

**Minh hoạ các đường MA trên cùng dữ liệu của một ngân hàng:**

In [130]:
def comparison_MA_4type(data, col='Đóng cửa', window_size=50):
    # Tính toán các loại trung bình động khác nhau
    data['SMA'] = SMA(data, period=window_size, column=col)
    data['EMA'] = EMA(data, period=window_size, column=col)
    data['WMA'] = WMA(data, period=window_size, column=col)
    data['VWMA'] = VWMA(data, period=window_size, column=col)

    # Tạo biểu đồ nến với các loại trung bình động khác nhau
    fig = go.Figure()

    # Biểu đồ nến
    fig.add_trace(go.Candlestick(x=data['Ngày'],
                                 open=data['Mở cửa'],
                                 high=data['Cao nhất'],
                                 low=data['Thấp nhất'],
                                 close=data[col],
                                 name='Giá',
                                 opacity=0.5))

    # SMA
    fig.add_trace(go.Scatter(x=data['Ngày'],
                             y=data['SMA'],
                             mode='lines',
                             name='SMA',
                             line=dict(color='olivedrab', width=2),
                             visible='legendonly'))

    # EMA
    fig.add_trace(go.Scatter(x=data['Ngày'],
                             y=data['EMA'],
                             mode='lines',
                             name='EMA',
                             line=dict(color='orangered', width=2),
                             visible=True))

    # WMA
    fig.add_trace(go.Scatter(x=data['Ngày'],
                             y=data['WMA'],
                             mode='lines',
                             name='WMA',
                             line=dict(color='darkcyan', width=2),
                             visible='legendonly'))

    # VWMA
    fig.add_trace(go.Scatter(x=data['Ngày'],
                             y=data['VWMA'],
                             mode='lines',
                             name='VWMA',
                             line=dict(color='mediumvioletred', width=2),
                             visible='legendonly'))

    # Cập nhật bố cục
    fig.update_layout(title='Biểu đồ nến với Các Trung Bình Động Khác Nhau',
                      xaxis_title='Ngày',
                      yaxis_title='Giá',
                      width=1200,
                      height=900)

    # Xóa output hiện tại và hiển thị biểu đồ mới
    clear_output(wait=True)
    display(control_widgets1)
    fig.show()

# Tạo widget cho tương tác
size_widget1 = widgets.Dropdown(
    options=[15, 20, 30, 50, 100, 120, 200],
    description='Kỳ hạn:',
    value=50
)

apply_button1 = widgets.Button(description="Áp dụng")

# Nhóm các widget trong một hàng
control_widgets1 = widgets.HBox([size_widget1, apply_button1])

# Hàm để cập nhật biểu đồ dựa trên kích thước cửa sổ
def update_plot(button):
    comparison_MA_4type(data, 'Đóng cửa', size_widget1.value)

# Liên kết nhấp chuột vào nút với hàm update_plot
apply_button1.on_click(update_plot)

# Hiển thị các widget
display(control_widgets1)

# Biểu đồ ban đầu
comparison_MA_4type(data, 'Đóng cửa', size_widget1.value)

HBox(children=(Dropdown(description='Kỳ hạn:', index=3, options=(15, 20, 30, 50, 100, 120, 200), value=50), Bu…

#### **2. Cách xác định tín hiện giao dịch (mua/ bán) bằng MA**

##### **2.1. Tín hiệu Buy (Mua)**

1. **Golden Cross**: Khi đường MA ngắn hạn (ví dụ: 50 ngày) cắt lên trên đường MA dài hạn (ví dụ: 200 ngày), đây là tín hiệu tăng dài hạn => nên mua.
2. **Giá vượt lên trên MA**: Khi giá vượt lên trên đường MA (đặc biệt là MA dài hạn), đó có thể là tín hiệu mua.

##### **2.2. Tín hiệu Sell (Bán)**

1. **Death Cross**: Khi đường MA ngắn hạn cắt xuống dưới đường MA dài hạn, đây là tín hiệu bán mạnh.
2. **Giá cắt xuống dưới MA**: Khi giá cắt xuống dưới đường MA, đó có thể là tín hiệu bán.

##### **2.3. Kết hợp nhiều MA để xác định tín hiệu**

- **Double MA Crossover**: Sử dụng hai đường MA, một ngắn hạn và một dài hạn, để xác định tín hiệu. Khi MA ngắn hạn cắt lên trên MA dài hạn, tín hiệu mua; khi cắt xuống dưới, tín hiệu bán.
- **Triple MA Crossover**: Sử dụng ba đường MA (ngắn hạn, trung hạn, và dài hạn) để xác định tín hiệu mạnh hơn. Ví dụ, khi MA ngắn hạn cắt lên trên cả MA trung hạn và dài hạn, tín hiệu mua; khi cắt xuống dưới, tín hiệu bán.

In [123]:
# Hàm tổng hợp 4 đường MA
def MA(df, period=30, column="Price", ma_type="SMA"):
    if ma_type == "SMA":
        return SMA(df, period, column)
    elif ma_type == "EMA":
        return EMA(df, period, column)
    elif ma_type == "WMA":
        return WMA(df, period, column)
    elif ma_type == "VWMA":
        return VWMA(df, period, column)
    else:
        raise ValueError("Invalid ma_type. Use 'SMA', 'EMA', 'WMA', or 'VWMA'.")

In [129]:
# Hàm mua/bán với các widget điều khiển
def buy_n_sell(data, col='Đóng cửa', period1=20, period2=50, period3=200, MA_type='SMA'):
    # Tạo một bản sao của DataFrame để tránh thay đổi dữ liệu gốc
    df = data.copy()
    
    # Tính toán các đường MA
    df['line1'] = MA(df, period=period1, column=col, ma_type=MA_type)
    df['line2'] = MA(df, period=period2, column=col, ma_type=MA_type)
    df['line3'] = MA(df, period=period3, column=col, ma_type=MA_type)

    # Điều kiện mua bán
    df['Signal'] = np.where(df["line1"] > df["line2"], 1, 0)
    df['Position'] = df['Signal'].diff()
    df['Buy'] = np.where(df['Position'] == 1, df[col], np.nan)
    df['Sell'] = np.where(df['Position'] == -1, df[col], np.nan)

    # Golden Cross và Death Cross
    df['Golden_Signal'] = np.where(df["line2"] > df["line3"], 1, 0)
    df['Golden_Position'] = df['Golden_Signal'].diff()
    
    df['Golden_Buy'] = np.where(df['Golden_Position'] == 1, df[col], np.nan)
    df['Death_Sell'] = np.where(df['Golden_Position'] == -1, df[col], np.nan)

    # Tạo biểu đồ nến và điểm mua/bán
    fig = go.Figure()

    # Candlestick
    fig.add_trace(go.Candlestick(x=df['Ngày'],
                                  open=df['Mở cửa'],
                                  high=df['Cao nhất'],
                                  low=df['Thấp nhất'],
                                  close=df[col],
                                  name='Giá',
                                  opacity=0.5))

    # Đường MA
    fig.add_trace(go.Scatter(x=df['Ngày'],
                             y=df['line1'],
                             mode='lines',
                             name=f'MA ngắn hạn {period1}',
                             line=dict(color='royalblue')))

    fig.add_trace(go.Scatter(x=df['Ngày'],
                             y=df['line2'],
                             mode='lines',
                             name=f'MA trung hạn {period2}',
                             line=dict(color='darkorange')))

    fig.add_trace(go.Scatter(x=df['Ngày'],
                             y=df['line3'],
                             mode='lines',
                             name=f'MA dài hạn {period3}',
                             line=dict(color='seagreen')))

    # Buy Signal
    fig.add_trace(go.Scatter(x=df['Ngày'][df['Position'] == 1],
                             y=df[col][df['Position'] == 1],
                             mode='markers',
                             marker=dict(symbol='triangle-up', color='green', size=12),
                             name='Buy Signal'))

    # Sell Signal
    fig.add_trace(go.Scatter(x=df['Ngày'][df['Position'] == -1],
                             y=df[col][df['Position'] == -1],
                             mode='markers',
                             marker=dict(symbol='triangle-down', color='red', size=12),
                             name='Sell Signal'))
    
    # Golden Buy Signal
    fig.add_trace(go.Scatter(x=df['Ngày'][df['Golden_Position'] == 1],
                             y=df[col][df['Golden_Position'] == 1],
                             mode='markers',
                             marker=dict(symbol='triangle-up', color='gold', size=16),
                             name='Golden Buy Signal',
                             visible='legendonly'))

    # Death Sell Signal
    fig.add_trace(go.Scatter(x=df['Ngày'][df['Golden_Position'] == -1],
                             y=df[col][df['Golden_Position'] == -1],
                             mode='markers',
                             marker=dict(symbol='triangle-down', color='maroon', size=16),
                             name='Death Sell Signal',
                             visible='legendonly'))

    # Thiết lập bố cục cho biểu đồ
    fig.update_layout(title='Biểu đồ nến với tín hiệu mua/bán',
                      xaxis_title='Ngày',
                      yaxis_title='Giá',
                      autosize=True,
                      width=None,
                      height=800)

    # Clear the current output and display the new figure
    clear_output(wait=True)
    fig.show()

# Tạo widgets cho việc điều khiển
period_widget1 = widgets.Dropdown(
    options=[20, 50, 200],
    description='Kỳ hạn 1:',
    value=20
)

period_widget2 = widgets.Dropdown(
    options=[20, 50, 200],
    description='Kỳ hạn 2:',
    value=50
)

period_widget3 = widgets.Dropdown(
    options=[20, 50, 200],
    description='Kỳ hạn 3:',
    value=200
)

apply_button = widgets.Button(description="Áp dụng")

# Hàm để cập nhật biểu đồ dựa trên giá trị kỳ hạn
def update_plot(button):
    buy_n_sell(data, col='Đóng cửa', 
                period1=period_widget1.value, 
                period2=period_widget2.value, 
                period3=period_widget3.value, 
                MA_type='SMA')

# Liên kết nút nhấn với hàm cập nhật biểu đồ
apply_button.on_click(update_plot)

# Hiển thị các widgets
control_widgets = widgets.HBox([period_widget1, period_widget2, period_widget3, apply_button])
display(control_widgets)

# Biểu đồ ban đầu
buy_n_sell(data, col='Đóng cửa', period1=20, period2=50, period3=200, MA_type='SMA')